<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Anayra" failures="1" tests="5" name="Parallel.ParallelRun" time="151.036" errors="0" timestamp="2024-03-19T09:24:01 EDT" skipped="0">
  <testcase classname="Parallel.ParallelRun" name="runScenario" time="27.798"/>
  <testcase classname="Parallel.ParallelRun" name="runScenario" time="38.770"/>
  <testcase classname="Parallel.ParallelRun" name="runScenario" time="29.348"/>
  <testcase classname="Parallel.ParallelRun" name="runScenario" time="26.678"/>
  <testcase classname="Parallel.ParallelRun" name="runScenario" time="28.442">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertTrue(Assert.java:53)
at Parallel.HomePageSteps.homepage_section_count_should_be(HomePageSteps.java:47)
at âœ½.Homepage section count should be 13(classpath:Parallel/HomePage.feature:29)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- Parallel.ParallelRun -->
